project:
  type: website

website:
  title: "NHANES Obesity Trends"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: explanation.qmd
        text: Explanation
      - href: sugar.qmd
        text: Sugar
      - href: carbs-and-fats.qmd
        text: Carbs and Fats

format:
  html:
    theme: cosmo
