project:
  type: website

website:
  title: "NHANES Obesity Trends"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: explanation.qmd
        text: Explanation
      - href: sugar.qmd
        text: Sugar
      - href: carbs.qmd
        text: Carbs
      - href: fats.qmd
        text: Fats
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
